version: "3"
services:
  postgres:
    image: "postgres:alpine"
  redis:
    image: "redis:alpine"
  app:
    build: .
    restart: always
    command: python -m flask run -h 0.0.0.0
    environment:
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    volumes:
      - .:/app
